# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_name', models.TextField()),
                ('man_sername', models.TextField()),
                ('man_age', models.IntegerField()),
            ],
        ),
    ]
